"""
SetGAN — Generative Adversarial Network for lottery set generation.

Architecture
------------
Generator
  Input  : z (noise, dim=noise_dim) + cond (fused distribution + memory state)
  Layers : FC → LeakyReLU → FC → LeakyReLU → FC → sigmoid
  Output : (TOTAL=80,) logit scores → sample PICK numbers without replacement

Discriminator
  Input  : one_hot set (TOTAL,) + cond (same conditioning vector as Generator)
  Layers : FC → LeakyReLU → FC → LeakyReLU → FC → sigmoid
  Output : scalar probability that the set is "real" (drawn from actual data)

Training (non-saturating GAN, gradient-free via ES perturbation)
  At each walk-forward step:
  - Real samples  : one-hot encoded actual draw (and recent history draws)
  - Fake samples  : sets generated by the Generator
  - Discriminator : updated to separate real from fake (ES-based weight update)
  - Generator     : updated to fool the Discriminator (ES-based weight update)

The ES (Evolution Strategy) update is a (+1, λ)-ES with antithetic sampling,
making the GAN trainable with pure NumPy without backprop.
"""
from __future__ import annotations

from typing import List, Optional, Tuple

import numpy as np

TOTAL = 80
PICK = 15


def _leaky_relu(x: np.ndarray, alpha: float = 0.2) -> np.ndarray:
    return np.where(x >= 0, x, alpha * x)


def _sigmoid(x: np.ndarray) -> np.ndarray:
    return 1.0 / (1.0 + np.exp(-np.clip(x, -20, 20)))


class MLP:
    """Simple fully-connected network stored as a list of (W, b) tuples."""

    def __init__(self, layer_sizes: List[int], seed: int = 0) -> None:
        self.layer_sizes = layer_sizes
        rng = np.random.default_rng(seed)
        self.layers: List[Tuple[np.ndarray, np.ndarray]] = []
        for i in range(len(layer_sizes) - 1):
            fan_in = layer_sizes[i]
            scale = np.sqrt(2.0 / fan_in)
            W = rng.normal(0, scale, (layer_sizes[i + 1], layer_sizes[i]))
            b = np.zeros(layer_sizes[i + 1])
            self.layers.append((W, b))

    def forward(self, x: np.ndarray, output_activation: str = "leaky_relu") -> np.ndarray:
        h = x
        for i, (W, b) in enumerate(self.layers):
            h = W @ h + b
            is_last = i == len(self.layers) - 1
            if is_last:
                if output_activation == "sigmoid":
                    h = _sigmoid(h)
                elif output_activation == "tanh":
                    h = np.tanh(h)
                # else: linear
            else:
                h = _leaky_relu(h)
        return h

    def get_flat_params(self) -> np.ndarray:
        return np.concatenate([np.concatenate([W.flatten(), b]) for W, b in self.layers])

    def set_flat_params(self, params: np.ndarray) -> None:
        idx = 0
        new_layers = []
        for W, b in self.layers:
            nw = W.size
            nb = b.size
            new_W = params[idx : idx + nw].reshape(W.shape)
            idx += nw
            new_b = params[idx : idx + nb]
            idx += nb
            new_layers.append((new_W, new_b))
        self.layers = new_layers

    def n_params(self) -> int:
        return sum(W.size + b.size for W, b in self.layers)


class SetGenerator:
    """
    GAN Generator: (noise + conditioning) → (TOTAL,) score → sample pick numbers.

    Parameters
    ----------
    cond_dim   : dimension of the conditioning vector (fused_dist + memory_state)
    noise_dim  : latent noise dimension
    hidden_dim : width of hidden layers
    pick       : numbers to sample per set
    """

    def __init__(
        self,
        cond_dim: int,
        noise_dim: int = 32,
        hidden_dim: int = 128,
        pick: int = PICK,
        seed: int = 10,
    ) -> None:
        self.noise_dim = noise_dim
        self.cond_dim = cond_dim
        self.pick = pick
        input_dim = noise_dim + cond_dim
        self.net = MLP([input_dim, hidden_dim, hidden_dim, TOTAL], seed=seed)

    def generate(
        self,
        cond: np.ndarray,
        n_sets: int = 20,
        rng: Optional[np.random.Generator] = None,
        temperature: float = 1.0,
    ) -> List[List[int]]:
        """
        Generate n_sets lottery number sets.

        Returns list of sorted lists of self.pick integers in [1, TOTAL].
        """
        if rng is None:
            rng = np.random.default_rng()
        sets = []
        for _ in range(n_sets):
            z = rng.standard_normal(self.noise_dim)
            inp = np.concatenate([z, cond])
            logits = self.net.forward(inp, output_activation="linear")
            logits = logits / max(temperature, 1e-4)
            probs = np.exp(logits - logits.max())
            probs /= probs.sum()
            indices = rng.choice(TOTAL, size=self.pick, replace=False, p=probs)
            sets.append(sorted(int(i) + 1 for i in indices))
        return sets

    def score_distribution(self, cond: np.ndarray, n_samples: int = 50) -> np.ndarray:
        """
        Return an averaged (TOTAL,) probability vector by Monte-Carlo sampling.
        Used for single-best-set prediction.
        """
        rng = np.random.default_rng(42)
        total_probs = np.zeros(TOTAL)
        for _ in range(n_samples):
            z = rng.standard_normal(self.noise_dim)
            inp = np.concatenate([z, cond])
            logits = self.net.forward(inp, output_activation="linear")
            probs = np.exp(logits - logits.max())
            probs /= probs.sum()
            total_probs += probs
        return total_probs / n_samples


class SetDiscriminator:
    """
    GAN Discriminator: (one_hot_set + conditioning) → real/fake score.
    """

    def __init__(
        self,
        cond_dim: int,
        hidden_dim: int = 128,
        seed: int = 20,
    ) -> None:
        self.cond_dim = cond_dim
        input_dim = TOTAL + cond_dim
        self.net = MLP([input_dim, hidden_dim, hidden_dim // 2, 1], seed=seed)

    def score(self, one_hot_set: np.ndarray, cond: np.ndarray) -> float:
        inp = np.concatenate([one_hot_set, cond])
        return float(self.net.forward(inp, output_activation="sigmoid")[0])

    def score_batch(self, sets_one_hot: np.ndarray, cond: np.ndarray) -> np.ndarray:
        return np.array([self.score(s, cond) for s in sets_one_hot])


# ---------------------------------------------------------------------------
# ES-based GAN training step (gradient-free)
# ---------------------------------------------------------------------------

def _es_update_model(
    model,
    get_net_fn,
    loss_fn,
    sigma: float = 0.02,
    n_perturbations: int = 20,
    lr: float = 0.01,
) -> float:
    """
    (+1, λ)-ES with antithetic perturbations applied to model via get_net_fn.
    loss_fn(model) → scalar loss.  Minimises loss by perturbing model's flat params.
    Returns the baseline loss.
    """
    net = get_net_fn(model)
    params = net.get_flat_params()
    n = len(params)
    baseline_loss = loss_fn(model)

    grad_est = np.zeros(n)
    for _ in range(n_perturbations // 2):
        eps = np.random.standard_normal(n) * sigma
        net.set_flat_params(params + eps)
        loss_pos = loss_fn(model)
        net.set_flat_params(params - eps)
        loss_neg = loss_fn(model)
        grad_est += (loss_pos - loss_neg) * eps

    grad_est /= max(n_perturbations * sigma, 1e-12)
    net.set_flat_params(params - lr * grad_est)
    return float(baseline_loss)


def train_gan_step(
    generator: SetGenerator,
    discriminator: SetDiscriminator,
    cond: np.ndarray,
    actual_draw: set,
    recent_draws: List[set],
    n_fake: int = 16,
    sigma: float = 0.02,
    n_perturb: int = 20,
    gen_lr: float = 0.005,
    disc_lr: float = 0.008,
    rng: Optional[np.random.Generator] = None,
) -> Tuple[float, float]:
    """
    One GAN training step using actual_draw + recent draws as real samples.

    Returns (disc_loss, gen_loss) for monitoring.
    """
    if rng is None:
        rng = np.random.default_rng()

    # Build real one-hot samples from actual + recent draws
    real_samples = []
    for draw in [actual_draw] + list(recent_draws):
        oh = np.zeros(TOTAL)
        for num in draw:
            if 1 <= num <= TOTAL:
                oh[num - 1] = 1.0
        real_samples.append(oh)
    real_arr = np.array(real_samples)

    # Pre-generate fake samples (fixed for discriminator update)
    fake_sets = generator.generate(cond, n_sets=n_fake, rng=rng)
    fake_arr = np.zeros((n_fake, TOTAL))
    for j, s in enumerate(fake_sets):
        for num in s:
            fake_arr[j, num - 1] = 1.0

    # ---- Discriminator update ----
    def disc_loss(disc: SetDiscriminator) -> float:
        real_scores = disc.score_batch(real_arr, cond)
        fake_scores = disc.score_batch(fake_arr, cond)
        return float(
            -np.mean(np.log(real_scores + 1e-8))
            - np.mean(np.log(1 - fake_scores + 1e-8))
        )

    d_loss = _es_update_model(
        discriminator, lambda d: d.net, disc_loss,
        sigma=sigma, n_perturbations=n_perturb, lr=disc_lr,
    )

    # ---- Generator update ----
    def gen_loss(gen: SetGenerator) -> float:
        gen_sets = gen.generate(cond, n_sets=n_fake, rng=np.random.default_rng())
        g_fake = np.zeros((n_fake, TOTAL))
        for j, s in enumerate(gen_sets):
            for num in s:
                g_fake[j, num - 1] = 1.0
        d_scores = discriminator.score_batch(g_fake, cond)
        return float(-np.mean(np.log(d_scores + 1e-8)))

    g_loss = _es_update_model(
        generator, lambda g: g.net, gen_loss,
        sigma=sigma, n_perturbations=n_perturb, lr=gen_lr,
    )

    return d_loss, g_loss
