"""
SetScorer — post-generation filter that ranks candidate sets by estimated
probability of hitting 5+ numbers, and keeps only the top-K.

Five scoring signals (all pick-independent, work for any pick size):

1. fused_score     — sum of fused distribution scores for numbers in the set.
                     The primary signal: numbers the transformer rates highly.

2. attention_score — sum of MemoryBank number_attention for numbers in the set.
                     Boosts numbers that appeared frequently in recent actual draws.

3. pair_score      — average pairwise co-success score for numbers in the set.
                     Boosts sets whose numbers tend to appear together.

4. diversity_score — penalises sets that overlap heavily with already-chosen sets.
                     Ensures the kept sets cover different parts of the number space.

5. replay_score    — sum of ExperienceReplay success pattern scores for numbers
                     in the set. Reinforces historically high-hit number combinations.

Final score = weighted combination of the above. Sets are ranked descending;
the top-K are returned.

The filter is most useful when n_generate >> n_keep, e.g. generate 200 sets,
keep top 20.  The GAN provides diversity; the scorer selects the best.
"""
from __future__ import annotations

from typing import List, Optional, Tuple

import numpy as np

TOTAL = 80


class SetScorer:
    """
    Scores and filters a list of candidate sets.

    Parameters
    ----------
    fused_dist      : (80,) fused probability distribution from transformer
    memory          : MemoryBank instance (for attention + pair scores)
    replay_signal   : (80,) ExperienceReplay success pattern (optional)
    weights         : (fused, attention, pair, diversity, replay) — must sum ~1
    """

    def __init__(
        self,
        fused_dist: np.ndarray,
        memory,
        replay_signal: Optional[np.ndarray] = None,
        weights: Tuple[float, float, float, float, float] = (0.40, 0.20, 0.15, 0.10, 0.15),
    ) -> None:
        self.fused_dist = fused_dist / (fused_dist.sum() + 1e-12)
        self.attention = memory.get_number_attention()
        self.pair_boost = memory.get_pair_boost()
        self.pair_matrix = memory.pair_success.copy()
        mx = self.pair_matrix.max()
        if mx > 0:
            self.pair_matrix /= mx
        self.replay = replay_signal if replay_signal is not None else np.zeros(TOTAL)
        mx_r = self.replay.max()
        if mx_r > 0:
            self.replay = self.replay / mx_r
        self.weights = weights

    def score_set(self, nums: List[int], used_coverage: np.ndarray) -> float:
        """
        Score a single candidate set.

        nums           : list of integers 1–80
        used_coverage  : (80,) float array counting how many already-kept sets
                         include each number (for diversity penalty)
        """
        idx = [n - 1 for n in nums if 1 <= n <= TOTAL]
        if not idx:
            return 0.0

        w_f, w_a, w_p, w_d, w_r = self.weights

        # 1. Fused distribution score
        fused_s = float(self.fused_dist[idx].sum())

        # 2. Attention score
        att_s = float(self.attention[idx].mean())

        # 3. Pairwise co-success score (avg over all pairs in the set)
        pair_s = 0.0
        if len(idx) > 1:
            pairs = 0
            for i in range(len(idx)):
                for j in range(i + 1, len(idx)):
                    pair_s += self.pair_matrix[idx[i], idx[j]]
                    pairs += 1
            pair_s /= max(pairs, 1)

        # 4. Diversity penalty — how much does this set overlap with kept sets?
        overlap = float(used_coverage[idx].mean())
        div_s = 1.0 - overlap  # higher = more unique

        # 5. Replay signal score
        rep_s = float(self.replay[idx].mean())

        return w_f * fused_s + w_a * att_s + w_p * pair_s + w_d * div_s + w_r * rep_s

    def filter_top(
        self,
        candidate_sets: List[List[int]],
        top_k: int,
        min_score: float = 0.0,
    ) -> Tuple[List[List[int]], List[float]]:
        """
        Score all candidates and return the top-K sets with their scores.

        Parameters
        ----------
        candidate_sets : list of sets generated by GAN (or any source)
        top_k          : number of sets to keep
        min_score      : optional minimum score threshold (0 = keep all top-K)

        Returns
        -------
        (kept_sets, scores) both sorted descending by score
        """
        top_k = min(top_k, len(candidate_sets))
        used_coverage = np.zeros(TOTAL)
        scored: List[Tuple[float, List[int]]] = []

        for candidate in candidate_sets:
            s = self.score_set(candidate, used_coverage)
            scored.append((s, candidate))

        # Sort by score descending
        scored.sort(key=lambda x: -x[0])

        kept_sets: List[List[int]] = []
        kept_scores: List[float] = []

        for score, nums in scored:
            if len(kept_sets) >= top_k:
                break
            if score < min_score:
                break
            kept_sets.append(nums)
            kept_scores.append(score)
            # Update coverage so next set gets diversity penalty
            for n in nums:
                if 1 <= n <= TOTAL:
                    used_coverage[n - 1] += 1.0 / top_k

        return kept_sets, kept_scores
